california-civic-data-coalition/django-calaccess-raw-data

- calaccess_raw/management/commands/loadcalaccessrawfile.py
- calaccess_raw/models/campaign.py
> Fixed blank date candidates instead of filling in 1900

- .travis.yml
> Django1.8b1 builds. Fixes #78. 

- calaccess_raw/models/other.py
> Added docstring for AcronymsCd model. Closes #111.

- calaccess_raw/models/other.py
> added docstring for LobbyistFirstLobbyist2Cd #149

- calaccess_raw/models/other.py
> Added docstring for LobbyistFirm1Cd model.

- calaccess_raw/models/other.py
Might need to make a call to "Matt"
> added docstring for LobbyistFirmEmployer1Cd

- calaccess_raw/models/other.py
> Add docstring to BallotMeasuresCD model

- calaccess_raw/models/other.py
> Add docstring for LobbyistEmpLobbyist2Cd model

- calaccess_raw/models/other.py
> Add docstring for ReceivedFilingsCd model #152

- calaccess_raw/management/commands/cleancalaccessrawfile.py
Logs errors to directory `example/data/log/**filename**.errors.csv.
> Added error logging for CSV cleaner. For #49.

- calaccess_raw/models/campaign.py
- requirements_dev.txt
> Add __unicode__ for S496Cd

- calaccess_raw/models/common.py
The description for CvrE530Cd is blank [in the print docs](https://www.documentcloud.org/documents/1308002-cal-access-about.html#document/p9).
FilingsCd and FilerFilingsCd are documented.
> Docstrings for #106, #107, #109

- calaccess_raw/models/other.py
This function is documented as "JM needs to describe this table. He indicates it is for future use." in [page 107 of the print docs](https://www.documentcloud.org/documents/1308002-cal-access-about.html#document/p107).
> Documentation for FilersStatusTypesCd in #122

- calaccess_raw/models/campaign.py
Source: cal_format_201.pdf, page 19.
Closes #92
> Add choices to form_type field of LoanCd model.

- calaccess_raw/models/campaign.py
> Added unicode to S496Cd model

- calaccess_raw/models/campaign.py
Added unicode to CvrCampaignDisclosureCd model
> Added unicode to CvrCampaignDisclosureCd model

- calaccess_raw/models/campaign.py
Values from:
http://www.sos.ca.gov/campaign-lobbying/cal-access-resources/raw-data-campaign-finance-and-lobbying-activity/
Download: Guides to CAL-ACCESS data structure and fields (ZIP)
File: CalAccess-Documentation/CalFormat/cal_format_201.pdf
Unknown values may be invalid, also not listed in:
CalAccess-Documentation/DBInfo/MapCalFormat2Fields.pdf
> form type choices: Issues  #89 , #90

- calaccess_raw/models/campaign.py
Added unicode to Cvr2CampaignDisclosureCd model
> Added unicode to Cvr2CampaignDisclosureCd model

- calaccess_raw/models/campaign.py
Added unicode to these models:
RcptCd
Cvr3VerificationInfoCd
LoanCd
S401Cd
ExpnCd
F495P2Cd
F495P2Cd
DebtCd
S496Cd
SpltCd
> Added unicode to several campaign.py models

- calaccess_raw/models/lobbying.py
Add __unicode__ method for CvrRegistrationCd, Cvr2RegistrationCd, CvrLobbyDisclosureCd, Cvr2LobbyDisclosureCd
> Add __unicode__ method for classes

- calaccess_raw/models/base.py
You were literally looking over my shoulder, Ben.
> Remove deprecated abstract base class date models.

- calaccess_raw/models/other.py
> Added unicode method for ReportsCd table.

- calaccess_raw/models/lobbying.py
For class F690P2Cd(CalAccessBaseModel) @ 630
> Added unicode at line 660

- calaccess_raw/models/other.py
Barely anything in the official docs, but hey.
> Maloy and I are slamming some really helpful info into this model.

- calaccess_raw/models/campaign.py
> Added help_text for memo_refno

- calaccess_raw/models/campaign.py
> Update juris_cd help text

- calaccess_raw/models/lobbying.py
> Added help text for client_id field of the table LEMP

- calaccess_raw/models/lobbying.py
Fixed the original #917 commit and added #916
> Added documentation for `client_id` and `con_period`

- calaccess_raw/models/campaign.py
Added help text for Employer and "Memo Amount Flag"
> Help ticket #687 for table s498cd

- calaccess_raw/models/campaign.py
> Added documentation for ``did_exceed_dt`` field (no documentation)

- calaccess_raw/models/campaign.py
> Added documentation for "cntrb_prsnl_fnds_dt" field in F501502Cd data, issue #659

- calaccess_raw/models/lobbying.py
Integrate the values entered into the `bus_class` and `ind_class` fields of the ``CvrRegistrationCd`` lobbying model
> Choices for bus_class and ind_class

- calaccess_raw/models/campaign.py
> added documentation to the "elect_date" field

- calaccess_raw/models/campaign.py
tres_namf #558
tres_naml #559
tres_nams #560
tres_namt #561
> Help text for tres_namf, tres_naml, tres_nams, & tres_namt

- calaccess_raw/models/other.py
> Applied unique key "RPT_ID" to REPORTS

- calaccess_raw/models/other.py
> Adding unique key

- calaccess_raw/models/other.py
Ben stood over me and also, I learn fast.
> Unique ID key entered for HEADER_CD

- calaccess_raw/models/other.py
> Added unique field for FILER_ACRONYMS table

- calaccess_raw/models/campaign.py
> added unique key for ExpnCd to fix #1028

- calaccess_raw/models/campaign.py
> Closes #1023. Adds UNIQUE_KEY for CvrCampaignDisclosureCd

- calaccess_raw/models/lobbying.py
p.s. the example in the issue stores the column codes in a list, but you had me add them as a tuple yesterday, so i did that here, as well. is that correct?
> adds unique key to LattCd

- calaccess_raw/models/other.py
> Update models with unique key for FilerXrefCd model class

- calaccess_raw/models/campaign.py
Closes #1021 
| cmtte_type | count |
------------ | ----------
| P          |      539 |
| B          |     3375 |
| C          |    29779 |
| G          |    40490 |
|            |    92331 |
```sql
SELECT cmtte_type, COUNT(*)
FROM CVR_CAMPAIGN_DISCLOSURE_CD
GROUP BY 1
ORDER BY 2;
```
> Add choices tuple for cmtte_type fields

- calaccess_raw/management/commands/cleancalaccessrawfile.py
- calaccess_raw/management/commands/downloadcalaccessrawdata.py
- example/toolbox/management/commands/samplecalaccessrawdata.py
No reason not to, and it has fewer assumptions about the directory structure.
> Use makedirs instead of mkdir

- calaccess_raw/management/commands/downloadcalaccessrawdata.py
- calaccess_raw/management/commands/loadcalaccessrawfile.py
- calaccess_raw/models/campaign.py
- calaccess_raw/models/common.py
- calaccess_raw/models/lobbying.py
- calaccess_raw/tests.py
- tox.ini
For a reason I don't understand, `pep8` is passing in the main build but fails when I add a flag in my `resume` branch. When I run it locally on the `master` branch, I see a bunch of failures.
Resume branch failures (fewer than what I get in `master` branch when I run `pep8` locally)
I worked through the various `pep8` failures in the `master` branch, just submitting them here (and rebasing the `resume` branch on this)
> STY: pep8 fixes

- calaccess_raw/management/commands/loadcalaccessrawfile.py
The current `loadcalaccessrawfile` command acts as a database router: it determines which database to write to. However, Django has an entire [router system for multi-db apps](https://docs.djangoproject.com/en/1.9/topics/db/multi-db/#using-routers) that does this.
The enhancement here is:
* Create a `self.database` property, with command-line option (standard-ish in Django).
* Use Django's router to set the database, if `--database` is not used.
* Keep a special codepath for `dat`, since that seemed particular.
This would, for example, allow us to load raw data into a separate database than a production database.
> ENH: work better with multi-db apps.

- calaccess_raw/models/campaign.py
- calaccess_raw/models/lobbying.py
> set fields to maxlengths used in calaccess documentation

- calaccess_raw/models/lobbying.py
Added the page number for Cvr2RegistrationCd
> Updated documenation

- calaccess_raw/models/common.py
> Added DocumentCloud page references for SMRY table

- calaccess_raw/models/lobbying.py
Added in pages for documentcloud
> Updated file for lexp

- calaccess_raw/models/campaign.py
> Updated S496

- calaccess_raw/models/common.py
Documentation calls it "CVR_E530"
> Added documentation for the CvrE530Cd field

- calaccess_raw/models/campaign.py
Regarding issue https://github.com/california-civic-data-coalition/django-calaccess-raw-data/issues/1208
> Add doc cloud reference to Cvr3VerificationInfoCd

- calaccess_raw/models/lobbying.py
Re: issue https://github.com/california-civic-data-coalition/django-calaccess-raw-data/issues/1209
> Add doc cloud reference to LccmCd

- calaccess_raw/models/lobbying.py
> Added documentation for the LattCd field

- calaccess_raw/models/lobbying.py
> Added documentation reference for LobbyistEmployerFirms2Cd

- docs/conf.py
File is here https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/docs/_static/css/docs_style.css
> css filename needs a plural

- calaccess_raw/models/lobbying.py
> Added page for lobbying change log

- calaccess_raw/models/common.py
> Added DocumentCloud page number for FILING_ID

- calaccess_raw/models/lobbying.py
Re: https://github.com/california-civic-data-coalition/django-calaccess-raw-data/issues/1209
> Add doc cloud reference to LobbyistEmpLobbyist2Cd

- calaccess_raw/models/lobbying.py
Update info model LobbyistLothCd w/document cloud info
> LobbyistLothCd document cloud info

- calaccess_raw/models/lobbying.py
> Add definition to LobbyistContributions2Cd

- calaccess_raw/models/lobbying.py
* updated id format
* fixed page numbers
* added MapCalFormat2Fields reference
> Update CvrLobbyDisclosureCd DocumentCloud docs

- calaccess_raw/models/lobbying.py
Add document cloud info for LobbyistEmpLobbyist1Cd model
> LobbyistEmpLobbyist1Cd model info

- calaccess_raw/models/lobbying.py
Docs call it `LOBBYIST_FIRM1`
#1209
> Added documentation for the LobbyistFirm1Cd field

- calaccess_raw/models/lobbying.py
Re: https://github.com/california-civic-data-coalition/django-calaccess-raw-data/issues/1209
> Add doc cloud reference to LobbyistFirmLobbyist2Cd

- calaccess_raw/models/common.py
> Adding DocCloud references to `FilingsCd`

- calaccess_raw/models/common.py
> Add DocumentCloud page number for TextMemoCD

- calaccess_raw/models/lobbying.py
submitting "Added documentation to the lobbyistcontribution3 field" to the core team for inclusion
> Added documentation to the lobbyistcontribution3 field

- calaccess_raw/models/common.py
submitting "Added documentation to the lobbyistcontribution3 field" to the core team for inclusion
> Added documentation to the TextMemoCd field

- calaccess_raw/models/campaign.py
> Adding DocumentCloud pages for MapCalFormat2Fields to Loan class

- calaccess_raw/models/campaign.py
Page nos for MapCalFormats for RcptCd, Cvr3VerificationInfoCd, LoanCD, S401CD, ExpnCd
#1283
> Adding DocumentCloud pages for MapCalFormat2Fields

- calaccess_raw/models/lobbying.py
Added document cloud page reference for 'lobbyingchglogcd'
> Added document cloud page reference

- calaccess_raw/models/lobbying.py
added document could ref for LobbyistEmployer3Cd
> Doc cloud ref LobbyistEmployer3Cd

- calaccess_raw/models/lobbying.py
My first commit put the pages in the wrong place, also added page for the table list
> Update lobbying.py with proper page numbers

- calaccess_raw/models/other.py
FilingPeriodCd is on pages 74 and 75
> added FilingPeriodCd documentcloud pages

- calaccess_raw/models/other.py
added page 84 for start, took out end
> added page numbers for LegislativeSessionsCd

- calaccess_raw/models/lobbying.py
added pages on table list where Lobbyist_Employer2 and Lobbyist_Employer3
> added pages reference from table list

- calaccess_raw/models/other.py
added page 84 for start, took out end
> also adding table reference for #1211

- calaccess_raw/models/common.py
Added from https://www.documentcloud.org/documents/2711616-MapCalFormat2Fields.html
> Add some more DocumentCloud links to Hdr, Smry, Splt

- calaccess_raw/models/lobbying.py
> Added documentation for LobbyistEmpLobbyist2Cd field

- calaccess_raw/management/commands/downloadcalaccessrawdata.py
- calaccess_raw/management/commands/updatecalaccessrawdata.py
- calaccess_raw/models/tracking.py
- example/settings.py
Still unresolved: how to unique key and organize the files in the media directory.
> media archiving for #1206
